src/Csf.FileUpload/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace Csf.FileUpload.Models
{
    public class User
    {

        public int UserId { get; set; }
        [Required, Display(Name = "用户名")]
        public string UserName { get; set; }

        [Required, Display(Name = "密码")]
        [DataType(DataType.Password)]
        public string UserPwd { get; set; }

        [Required, Display(Name = "电话")]
        [DataType(DataType.PhoneNumber)]
        public string Tel { get; set; }

        [Required, Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Display(Name = "头像")]
        public string Avatar { get; set; }
    }
}

src/Csf.FileUpload/Controllers/FileUploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.AspNet.Hosting;
using Microsoft.Framework.DependencyInjection;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Csf.FileUpload.Controllers
{
    public class FileUploadController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            BindControls();
            return View(new Utils.FileUpload());
        }

        private void BindControls()
        {
            /// 0：为空 默认，
            /// 1：按年（yyyy）,
            /// 2：按月（yyyyMM）,
            /// 3：按日（yyyyMMdd),
            /// 4：按年月(yyyy/MM),
            /// 5：按年月日(yyyy/MM/dd),
            /// 6：按扩展名(ext)
            ViewBag.DNTypes = new List<SelectListItem>()
            {
                new SelectListItem() { Value="0", Text="默认" },
                new SelectListItem() { Value="1", Text="按年（yyyy）" },
                new SelectListItem() { Value="2", Text="月（yyyyMM）" },
                new SelectListItem() { Value="3", Text="按日（yyyyMMdd)" },
                new SelectListItem() { Value="4", Text="按年月(yyyy/MM)" },
                new SelectListItem() { Value="5", Text="按年月日(yyyy/MM/dd)" },
                new SelectListItem() { Value="6", Text="按扩展名(ext)" }
            };

            /// 0：原文件名，默认
            /// 1：Guid文件名，
            /// 2：yyyyMMddHHmmss+4位随机数，
            /// 3：yyyyMMddHHmmss+原文件名
            /// 4：8位随机字符（字母+数字）
            /// 5：4位随机字符+原文件名
            ViewBag.FNTypes = new List<SelectListItem>()
            {
                new SelectListItem() { Value="0", Text="默认(原文件名)" },
                new SelectListItem() { Value="1", Text="Guid文件名" },
                new SelectListItem() { Value="2", Text="yyyyMMddHHmmss+4位随机数" },
                new SelectListItem() { Value="3", Text="yyyyMMddHHmmss+原文件名" },
                new SelectListItem() { Value="4", Text="8位随机字符（字母+数字）" },
                new SelectListItem() { Value="5", Text="4位随机字符+原文件名" },
            };
        }

        [HttpPost]
        public async Task<IActionResult> Index(Utils.FileUpload m)
        {
            BindControls();
            if (ModelState.IsValid)
            {
                m.Set(".rar|.txt|.pdf|.doc|.jpeg|.jpg|.gif", 2);
                var isok = await m.SaveFileAsAsync(HttpContext);
                if (isok)
                {
                    //todo your code

                }
                else { ModelState.AddModelError("", m.ErrorMessage); }
            }
            return View(m);
        }


        public IActionResult CreateUser()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateUser(Models.User m)
        {
            if (ModelState.IsValid)
            {
                Utils.FileUpload upload = new Utils.FileUpload()
                {
                    SubDir = "avatar",
                    DNType = 5,
                    FromFile = Request.Form.Files.GetFile("img")    //前台文件域的name
                };
                upload.Set(".jpg|.bmp|.jpeg|.gif|.bmp");            //只能上传图片，并且大小为1M
                upload.SetFileName("csfplus");                      //自定义文件名,此时FNType无效

                var isok = await upload.SaveFileAsAsync(HttpContext);
                if (isok)
                {
                    //设置头像图片地址
                    m.Avatar = upload.TargetFilePath;

                    //todo your code
                    // ........
                    m.UserId = 123;

                    return View("Detail", m);
                }
                else
                    ModelState.AddModelError("", upload.ErrorMessage);
            }
            return View(m);
        }


        public IActionResult Js()
        {
            return View();
        }

        public IActionResult JsUpload(Utils.FileUpload upload)
        {
            if (ModelState.IsValid)
            {
                //upload.Set("")
                if (upload.SaveFileAsAsync(HttpContext).Result)
                    return Json(new { ret = 1, src = upload.TargetFilePath });
                else
                    return Json(new { ret = 0, msg = upload.ErrorMessage });
            }
            else
                return Json(new { ret = 0, msg = ModelState.ExpendErrors() });
        }

    }
}

src/Csf.FileUpload/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

namespace Csf.FileUpload.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View("~/Views/Shared/Error.cshtml");
        }
    }
}

src/Csf.FileUpload/Views/FileUpload/CreateUser.cshtml
@{
    ViewBag.Title = "添加用户";
}
@model Csf.FileUpload.Models.User
<h2>添加用户</h2>
<link href="~/lib/bootstrap-fileupload/bootstrap-fileupload.css" rel="stylesheet" />
<div>
    <form method="post" enctype="multipart/form-data">
        <div class="control-group">
            <label asp-for="UserName"></label>
            <input type="text" asp-for="UserName" class="form-control" />
            <span asp-validation-for="UserName" class="error"></span>
        </div>
        <div class="control-group">
            <label asp-for="UserPwd"></label>
            <input type="password" asp-for="UserPwd" class="form-control" />
            <span asp-validation-for="UserPwd" class="error"></span>
        </div>
        <div class="control-group">
            <label asp-for="Tel"></label>
            <input type="tel" asp-for="Tel" class="form-control" />
            <span asp-validation-for="Tel" class="error"></span>
        </div>
        <div class="control-group">
            <label asp-for="Email"></label>
            <input type="email" asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="error"></span>
        </div>
        <div class="control-group">
            <label asp-for="Avatar"></label>
            <div class="fileupload fileupload-new" data-provides="fileupload">
                <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">
                    <img data-src="holder.js/100%x100%" alt="图片缩略图" src="~/lib/bootstrap-fileupload/thumb.svg">
                </div>
                <div class="fileupload-preview fileupload-exists thumbnail"
                     style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                <div>
                    <span class="btn btn-file btn-info">
                        <span class="fileupload-new">选择图片</span>
                        <span class="fileupload-exists">更改</span>
                        <input type="file" name="img" />
                    </span>
                    <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">移除</a>
                </div>
                <span asp-validation-for="Avatar" class="error"></span>
            </div>
            <div asp-validation-summary="ValidationSummary.ModelOnly" class="error"></div>

            <button type="submit" class="btn  btn-default">提交保存</button>

    </form>
</div>
@section scripts{
    <script src="~/lib/bootstrap-fileupload/bootstrap-fileupload.js"></script>
}

src/Csf.FileUpload/Views/FileUpload/Detail.cshtml
@model Csf.FileUpload.Models.User
@{
    ViewBag.Title = "查看用户信息";
}
<h2>查看用户</h2>
<div>
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(a => a.UserId)</dt>
        <dd>@Model.UserId</dd>
        <dt>@Html.DisplayNameFor(a => a.UserName)</dt>
        <dd>@Model.UserName</dd>
        <dt>@Html.DisplayNameFor(a => a.Tel)</dt>
        <dd>@Model.Tel</dd>
        <dt>@Html.DisplayNameFor(a => a.Email)</dt>
        <dd>@Model.Email</dd>
        <dt>@Html.DisplayNameFor(a => a.Avatar)</dt>
        <dd><img data-src="holder.js/200*150" src="@Model.Avatar" /></dd>
    </dl>
</div>

src/Csf.FileUpload/Views/FileUpload/Index.cshtml
@{
    ViewBag.Title = "文件上传";
}
@model Csf.FileUpload.Utils.FileUpload
<h2>文件上传</h2>

<div>
    <form method="post" enctype="multipart/form-data">
        <div class="control-group">
            <label asp-for="SubDir"></label>
            <input type="text" asp-for="SubDir" class="form-control" />
        </div>
        <div class="control-group">
            <label asp-for="DNType"></label>
            <select asp-for="DNType" asp-items="ViewBag.DNTypes" class="form-control"></select>
        </div>
        <div class="control-group">
            <label asp-for="FNType"></label>
            <select asp-for="FNType" asp-items="ViewBag.FNTypes" class="form-control"></select>
        </div>
        <div class="control-group">
            <label asp-for="FromFile"></label>
            <input type="file" asp-for="FromFile" class="form-control" />
            <span asp-validation-for="FromFile" class="error"></span>
        </div>
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="error"></div>

        <button type="submit" class="btn  btn-default">上传</button>
        <br />上传成功后的路径为：<a href="@Model.TargetFilePath">@Model.TargetFilePath</a>
    </form>
</div>

src/Csf.FileUpload/Views/FileUpload/js.cshtml
@{
    ViewBag.Title = "ajax 文件上传";
}
<h2>js异步上传文件</h2>
<div>
    <div class="control-group">
        <label class="control-label">图片</label>
        <input type="text" id="inp-avatar" />
        <input type="button" value="上传图片" id="upload" class="btn" />
    </div>
    <div class="control-group">
        <label class="control-label">图片预览</label>
        <img id="img-avatar" style="max-height:200px;" />
    </div>
</div>
@section  scripts{
    <script src="~/js/jquery.upload.v2.js"></script>

    <script>
        $(function () {
            $("#upload").upload({
                action: "@Url.Action("JsUpload")",  //上传地址
                fileName: "fromfile",               //文件名称。用于后台接收
                params: {
                    subdir: 'img',
                    fntype: 4,
                    dntype: 5
                },                                  //参数
                accept: ".jpg,.png,.gif,.bmp",      //文件类型,前台js验证
                complete: function (data) {         //上传完成
                    eval('data=' + data);
                    if (data.ret == 1) {
                        $("#inp-avatar").val(data.src);
                        $("#img-avatar").prop("src", data.src);
                    } else
                        alert(data.msg)
                }
                //,
                //submit: function () {   //提交之前
                //}
            });
        })
    </script>
}

src/Csf.FileUpload/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/Csf.FileUpload/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/Csf.FileUpload/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/ASP-NET-Banners-01.png" alt="ASP.NET" class="img-responsive" />
            <div class="container">
                <div class="carousel-caption">
                    <p>
                        Learn how to build ASP.NET apps that can run anywhere.
                        <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                            Learn More
                        </a>
                    </p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/images/Banner-02-VS.png" alt="Visual Studio" class="img-responsive" />
            <div class="container">
                <div class="carousel-caption">
                    <p>
                        There are powerful new features in Visual Studio for building modern web apps.
                        <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                            Learn More
                        </a>
                    </p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/images/ASP-NET-Banners-02.png" alt="Package Management" class="img-responsive" />
            <div class="container">
                <div class="carousel-caption">
                    <p>
                        Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                        <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                            Learn More
                        </a>
                    </p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/images/Banner-01-Azure.png" alt="Microsoft Azure" class="img-responsive" />
            <div class="container">
                <div class="carousel-caption">
                    <p>
                        Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                        <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                            Learn More
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET 5 (MVC 6)</li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518007">Gulp</a> and <a href="http://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side resources</li>
            <li>Theming using <a href="http://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>New concepts</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of ASP.NET 5</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518008">Fundamentals in ASP.NET 5</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517849">Client-Side Development using npm, Bower and Gulp</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517850">Develop on different platforms</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Customize app</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398600">Add Controllers and Views</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398602">Add Data using EntityFramework</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398603">Add Authentication using Identity</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517848">Manage client-side packages using Bower/ Gulp</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Deploy</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517851">Run your app locally</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517852">Run your app on .NET Core</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517853">Run commands in your app</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

src/Csf.FileUpload/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Csf.FileUpload</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-touch-carousel/dist/css/bootstrap-touch-carousel.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="hidden" asp-fallback-test-property="visibility" asp-fallback-test-value="hidden" />
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap-touch-carousel/0.8.0/css/bootstrap-touch-carousel.css"
              asp-fallback-href="~/lib/bootstrap-touch-carousel/css/bootstrap-touch-carousel.css"
              asp-fallback-test-class="carousel-caption" asp-fallback-test-property="display" asp-fallback-test-value="none" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">Csf.FileUpload</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-controller="FileUpload" asp-action="Index">文件上传</a></li>
                    <li><a asp-controller="FileUpload" asp-action="CreateUser">添加用户</a></li>
                    <li><a asp-controller="FileUpload" asp-action="js">异步上传</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2015 - Csf.FileUpload</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/hammer.js/hammer.js"></script>
        <script src="~/lib/bootstrap-touch-carousel/dist/js/bootstrap-touch-carousel.js"></script>
        <script src="~/lib/holderjs/holder.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/hammer.js/2.0.4/hammer.min.js"
                asp-fallback-src="~/lib/hammer.js/hammer.js"
                asp-fallback-test="window.Hammer">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap-touch-carousel/0.8.0/js/bootstrap-touch-carousel.js"
                asp-fallback-src="~/lib/bootstrap-touch-carousel/dist/js/bootstrap-touch-carousel.js"
                asp-fallback-test="window.Hammer && window.Hammer.Instance">
        </script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/holderjs/holder.min.js"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>